TITLE = 'Snake Game AI'

RECORD_TEXT = 'Maior pontuacao recorde: 0'
SCORE_TEXT = 'Maior pontuacao da geracao: 0'   
ALIVE_TEXT = 'Individuos vivos: 0'      
GENERATION_TEXT = 'Geracoes passadas: 0'

DELAY = int(1000 / 500)
LIVES = 3

GAMES_ROW_GRID = 6
GAMES_COLUMN_GRID = 10

GAME_SIZE = 150
BEST_GAME_SIZE = 300
GAME_GRID = 20

CHART_SIZE = 300
CHART_GRID = 10

NEURAL_NETWORK_SIZE = 300
NEURON_SIZE = 25

PADDING = 5

LINE_WIDTH = 2

DEFAULT_FONT = ('Minecraft', 15)
GAME_FONT = ('Minecraft', int(GAME_SIZE / 11))
NEURON_FONT = ('Minecraft', int(NEURON_SIZE / 4))

BLUE_COLOR = '#4430BE'
GREEN_COLORS = ['#7ECE6A', '#87D973']
RED_COLOR = '#BE3049'
LIGHT_COLOR = '#FFF'
DARK_COLOR = '#373737'
BG_COLOR = '#292929'

INPUT_LAYER_SIZE = 6
HIDDEN_LAYER_SIZES = [5, 5]
OUTPUT_LAYER_SIZE = 4
ACTIVATION_FUNCTION = lambda x: max(0, x)

BEST_PLAYERS_SELECT = 3

DATA_FILE = './save'