GAMES_GRID = 7

GAME_GRID = 20
GAME_SIZE = 130

PADDING = 5

NEURAL_NETWORK_WIDTH = 265
NEURAL_NETWORK_HEIGHT = 380
NEURON_SIZE = 23

CHART_SIZE = 265
CHART_GRID = 10

LINE_WIDTH = 2

BEST_GAME_SIZE = 265

DEFAULT_FONT = ('Minecraft', 15)

GAME_FONT = ('Minecraft', int(GAME_SIZE / 10))
NEURON_FONT = ('Minecraft', int(NEURON_SIZE / 4))

BLUE_COLOR = '#4430BE'
GREEN_COLORS = ['#7ECE6A', '#87D973']
RED_COLOR = '#BE3049'
BLACK_COLOR = '#373737'
WHITE_COLOR = '#FFF'

FPS = 200

LIVES = 3

BIAS = 1

INPUT_LAYER_SIZE = 16
HIDDEN_LAYER_SIZES = [10, 10]
OUTPUT_LAYER_SIZE = 4

ACTIVATION_FUNCTION = lambda x: max(0, x)

BEST_PLAYERS = 3

BEST_SCORE_TEXT = 'Melhor pontuacao recorde: 0'
CURRENT_BEST_SCORE_TEXT = 'Melhor pontuacao atual: 0'   
CURRENT_ALIVE_TEXT = 'Individuos vivos: 0'      
PAST_GENERATIONS_TEXT = 'Geracoes passadas: 0'

FILE_SAVE_PATH = './save'