GAMES_HORIZONTAL_GRID = 7
GAMES_VERTICAL_GRID = 6

GAME_GRID = 20

GAME_SIZE = 150

PADDING = 10

LINE_WIDTH = 2

CIRCLE_SIZE = 30

CHART_SIZE = 400
CHART_GRID = 10

NEURAL_NETWORK_SIZE = 400

BEST_GAME_SIZE = 400

FONT_CONFIG = ('Minecraft', int(GAME_SIZE / 10))
NEURON_FONT_CONFIG = ('Minecraft', 8)

FPS = 80

BLUE_COLOR = '#4430BE'
GREEN_COLORS = ['#7ECE6A', '#87D973']
RED_COLOR = '#BE3049'
BLACK_COLOR = '#373737'
WHITE_COLOR = '#FFF'
GRAY_COLOR = '#CCC'

NEURAL_NETWORK_BIAS = 1

INPUT_LAYER_SIZE = 10
HIDDEN_LAYER_SIZES = [12, 12]
OUTPUT_LAYER_SIZE = 4

TOP_PLAYERS = 3

FILE_SAVE_PATH = './save.txt'


BEST_SCORE_TEXT = 'Melhor pontuacao recorde: 0'
CURRENT_BEST_SCORE_TEXT = 'Melhor pontuacao atual: 0'   
CURRENT_ALIVE_TEXT = 'Individuos vivos: 0'      
PAST_GENERATIONS_TEXT = 'Geracoes passadas: 0'