BIAS = 1

NEURAL_NETWORK_WIDTH = 500
NEURAL_NETWORK_HEIGHT = 800

NEURON_VERTICAL_MARGIN = 5
NEURON_HORIZONTAL_MARGIN = 80

NEURON_CONNECTION_SIZE = 3
NEURON_SIZE = 40
NEURON_CENTER_SIZE = int(NEURON_SIZE / 2)

INPUT_LAYER_SIZE = 2
HIDDEN_LAYER_SIZES = [10, 10]
OUTPUT_LAYER_SIZE = 4