BIAS = 1

NEURAL_NETWORK_WIDTH = 400
NEURAL_NETWORK_HEIGHT = 500

NEURON_VERTICAL_MARGIN = 10
NEURON_HORIZONTAL_MARGIN = 50

NEURON_CONNECTION_SIZE = 3
NEURON_SIZE = 40
NEURON_CENTER_SIZE = int(NEURON_SIZE / 2)

INPUT_LAYER_SIZE = 2
HIDDEN_LAYER_SIZES = [8, 8]
OUTPUT_LAYER_SIZE = 4